import Script from 'next/script'
// import './globals.css'

export const metadata = {
  title: 'Art Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key="SB-Mid-client-XravRxhAaythPuaC" />
    </html>
  )
}
